Play travis
Otus-DevOps-2021-05/andrushke88_infra pull request #1
Opened 2021-06-17 15:35 UTC by andrushke88

2021-06-17 18:11 UTC, mrgreyves requested changes
Здравствуйте!) Вам стоит свериться с методичкой, не хватает некоторых файлов. ДЗ возвращаю на доработку.

2021-06-17 18:11 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Хммм....

2021-06-17 22:29 UTC, andrushke88 commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Пофиксил несоответствия, чекните как будет время

2021-06-18 15:36 UTC, mrgreyves approved these changes
Здравствуйте!) Вот теперь все корректно, апрув!)

2021-06-22 10:31 UTC, merged